# Generated by Django 4.2.2 on 2023-07-04 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sneakers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('price', models.FloatField(blank=True)),
                ('description', models.CharField(max_length=100)),
                ('image', models.URLField(blank=True)),
                ('in_stock', models.BooleanField(blank=True)),
            ],
        ),
    ]
